{{- if not .Values.mongodb.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-mongodb
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.mongodb.secretKey }}: {{ .Values.mongodb.uri | quote }}
{{- end }}
