appName: hello-world-springbootapp

image:
  repository: quay.io/REPLACE_ME/hello-world-springbootapp
  tag: latest
  pullPolicy: IfNotPresent

replicas: 1
containerPort: 8080

route:
  enabled: true
  host: ""
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
